name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  ci:
    name: "Nix CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs-chanel:nixos-unstable

    # TODO: Add formatter
    - name: Run nixfmt
      run: nix run nixpkgs#nixfmt-rfc-style -- --check .

    - name: Run dead code detection
      run: nix run nixpkgs#deadnix -- --fail .

    - name: Run statix linter
      run: nix run nixpkgs#statix -- check

    - name: Build config
      run: nix build .#nixosConfigurations.nixos.config.system.build.toplevel

    - name: Build home-manager
      run: nix run nixpkgs#home-manager -- switch --flake .#pesho
